### ISSUE TITLE
READMEにAccept-Languageの内容が記述されていません

### ISSUE THREAD

**Issue by ichiki1023** [BaguettePHP/http-accept-language#4]
READMEにOSSの内容が書かれていないためわかりづらく、以下のURLの資料を参考にしました。READMEに資料の内容を追記お願い致します。
http://www.slideshare.net/tadsan/accept-language
## サンプル

Accept-Languageは地域ごとに言語を特定することが出来ます。
例えば以下のようにどこの地域からアクセスされたのか判別し、正しい内容を返すことが出来ます。
　　
日本からのアクセス → こんにちは
英語圏からのアクセス → Hello
　　
参考URL:  http://www.slideshare.net/tadsan/accept-language

**Comment by zonuexe** [comment]
@satoichiki
This library is not intended for people who do not know the HTTP.
And your explanation is inaccurate.

I think that abstract example should be described in README. What do you think?
